export const DEMO_DATA = {
  nodes: [
    {id:'task',              label:'Task',              scope:'global',            core:true,
     fields:[{name:'number',label:'Number',type:'string'},{name:'short_description',label:'Short description',type:'string'},{name:'state',label:'State',type:'integer'},{name:'priority',label:'Priority',type:'integer'},{name:'assigned_to',label:'Assigned to',type:'reference'},{name:'assignment_group',label:'Assignment group',type:'reference'},{name:'opened_at',label:'Opened',type:'glide_date_time'},{name:'closed_at',label:'Closed',type:'glide_date_time'},{name:'cmdb_ci',label:'Configuration item',type:'reference'}]},
    {id:'incident',          label:'Incident',          scope:'global',            core:true,
     fields:[{name:'impact',label:'Impact',type:'integer'},{name:'urgency',label:'Urgency',type:'integer'},{name:'severity',label:'Severity',type:'integer'},{name:'category',label:'Category',type:'string'},{name:'subcategory',label:'Subcategory',type:'string'},{name:'problem_id',label:'Problem',type:'reference'},{name:'knowledge',label:'KB article',type:'reference'},{name:'resolved_at',label:'Resolved',type:'glide_date_time'}]},
    {id:'problem',           label:'Problem',           scope:'global',            core:true,
     fields:[{name:'known_error',label:'Known error',type:'boolean'},{name:'workaround',label:'Workaround',type:'string'},{name:'fix_notes',label:'Fix notes',type:'string'},{name:'change_id',label:'Change',type:'reference'},{name:'problem_state',label:'Problem state',type:'integer'}]},
    {id:'change_request',    label:'Change Request',    scope:'global',            core:true,
     fields:[{name:'type',label:'Type',type:'string'},{name:'risk',label:'Risk',type:'integer'},{name:'impact',label:'Impact',type:'integer'},{name:'start_date',label:'Planned start',type:'glide_date_time'},{name:'end_date',label:'Planned end',type:'glide_date_time'},{name:'cab_required',label:'CAB required',type:'boolean'},{name:'phase',label:'Phase',type:'string'}]},
    {id:'sc_request',        label:'Service Request',   scope:'global',            core:true,
     fields:[{name:'requested_for',label:'Requested for',type:'reference'},{name:'due_date',label:'Due date',type:'glide_date_time'},{name:'special_instructions',label:'Special instructions',type:'string'}]},
    {id:'sc_req_item',       label:'Requested Item',    scope:'global',            core:false,
     fields:[{name:'cat_item',label:'Catalog item',type:'reference'},{name:'quantity',label:'Quantity',type:'integer'},{name:'price',label:'Price',type:'currency'},{name:'request',label:'Request',type:'reference'},{name:'stage',label:'Stage',type:'string'}]},
    {id:'sc_task',           label:'Catalog Task',      scope:'global',            core:false,
     fields:[{name:'request_item',label:'Requested item',type:'reference'},{name:'order',label:'Order',type:'integer'}]},
    {id:'cmdb_ci',           label:'Configuration Item',scope:'global',            core:true,
     fields:[{name:'name',label:'Name',type:'string'},{name:'asset_tag',label:'Asset tag',type:'string'},{name:'serial_number',label:'Serial number',type:'string'},{name:'install_status',label:'Install status',type:'integer'},{name:'operational_status',label:'Operational status',type:'integer'},{name:'support_group',label:'Support group',type:'reference'},{name:'managed_by',label:'Managed by',type:'reference'},{name:'location',label:'Location',type:'reference'},{name:'environment',label:'Environment',type:'string'}]},
    {id:'sys_user',          label:'User',              scope:'global',            core:true,
     fields:[{name:'user_name',label:'User ID',type:'string'},{name:'first_name',label:'First name',type:'string'},{name:'last_name',label:'Last name',type:'string'},{name:'email',label:'Email',type:'string'},{name:'active',label:'Active',type:'boolean'},{name:'department',label:'Department',type:'reference'},{name:'manager',label:'Manager',type:'reference'},{name:'roles',label:'Roles',type:'string'}]},
    {id:'sys_user_group',    label:'Group',             scope:'global',            core:true,
     fields:[{name:'name',label:'Name',type:'string'},{name:'description',label:'Description',type:'string'},{name:'manager',label:'Manager',type:'reference'},{name:'active',label:'Active',type:'boolean'},{name:'type',label:'Type',type:'string'}]},
    {id:'cmdb_ci_server',    label:'Server',            scope:'global',            core:false,
     fields:[{name:'cpu_count',label:'CPU count',type:'integer'},{name:'ram',label:'RAM (MB)',type:'integer'},{name:'os',label:'OS',type:'string'},{name:'os_version',label:'OS version',type:'string'},{name:'ip_address',label:'IP address',type:'string'},{name:'fqdn',label:'FQDN',type:'string'}]},
    {id:'cmdb_ci_appl',      label:'Application',       scope:'global',            core:false,
     fields:[{name:'version',label:'Version',type:'string'},{name:'install_date',label:'Install date',type:'glide_date'},{name:'vendor',label:'Vendor',type:'reference'},{name:'business_criticality',label:'Business criticality',type:'integer'}]},
    {id:'cmdb_ci_service',   label:'Business Service',  scope:'global',            core:false,
     fields:[{name:'service_classification',label:'Classification',type:'string'},{name:'business_criticality',label:'Business criticality',type:'integer'},{name:'used_for',label:'Used for',type:'string'}]},
    {id:'kb_knowledge',      label:'Knowledge Article', scope:'global',            core:false,
     fields:[{name:'number',label:'Number',type:'string'},{name:'short_description',label:'Title',type:'string'},{name:'text',label:'Article body',type:'html'},{name:'category',label:'Category',type:'reference'},{name:'valid_to',label:'Valid to',type:'glide_date'},{name:'flagged',label:'Flagged',type:'boolean'}]},
    {id:'sn_hr_core_case',   label:'HR Case',           scope:'sn_hr_core',        core:false,
     fields:[{name:'subject_person',label:'Subject person',type:'reference'},{name:'hr_service',label:'HR service',type:'reference'},{name:'hr_profile',label:'HR profile',type:'reference'},{name:'opened_for',label:'Opened for',type:'reference'}]},
    {id:'sn_customerservice_case',label:'CSM Case',     scope:'sn_customerservice',core:false,
     fields:[{name:'account',label:'Account',type:'reference'},{name:'contact',label:'Contact',type:'reference'},{name:'product',label:'Product',type:'reference'},{name:'severity',label:'Severity',type:'integer'},{name:'escalation',label:'Escalation',type:'integer'}]},
    {id:'ast_contract',      label:'Contract',          scope:'global',            core:false,
     fields:[{name:'number',label:'Number',type:'string'},{name:'vendor',label:'Vendor',type:'reference'},{name:'start_date',label:'Start date',type:'glide_date'},{name:'end_date',label:'End date',type:'glide_date'},{name:'value',label:'Value',type:'currency'},{name:'contract_owner',label:'Contract owner',type:'reference'}]},
    {id:'alm_hardware',      label:'Hardware Asset',    scope:'global',            core:false,
     fields:[{name:'model',label:'Model',type:'reference'},{name:'assigned_to',label:'Assigned to',type:'reference'},{name:'purchase_date',label:'Purchase date',type:'glide_date'},{name:'warranty_expiration',label:'Warranty expiry',type:'glide_date'},{name:'lease_contract',label:'Lease contract',type:'reference'},{name:'cost',label:'Cost',type:'currency'}]},
    {id:'sn_risk_risk',      label:'Risk',              scope:'sn_risk',           core:false,
     fields:[{name:'title',label:'Title',type:'string'},{name:'risk_score',label:'Risk score',type:'integer'},{name:'treatment',label:'Treatment',type:'string'},{name:'affected_ci',label:'Affected CI',type:'reference'},{name:'owner',label:'Owner',type:'reference'}]},
    {id:'sys_user_role',     label:'Role',              scope:'global',            core:false,
     fields:[{name:'name',label:'Name',type:'string'},{name:'description',label:'Description',type:'string'},{name:'assignable_by',label:'Assignable by',type:'string'},{name:'elevated_privilege',label:'Elevated privilege',type:'boolean'}]},
  ],
  edges: [
    {source:'incident',     target:'task',           type:'extends',   label:'extends'},
    {source:'problem',      target:'task',           type:'extends',   label:'extends'},
    {source:'change_request',target:'task',          type:'extends',   label:'extends'},
    {source:'sc_request',   target:'task',           type:'extends',   label:'extends'},
    {source:'sc_req_item',  target:'task',           type:'extends',   label:'extends'},
    {source:'sc_task',      target:'task',           type:'extends',   label:'extends'},
    {source:'sn_hr_core_case',target:'task',         type:'extends',   label:'extends'},
    {source:'sn_customerservice_case',target:'task', type:'extends',   label:'extends'},
    {source:'cmdb_ci_server',target:'cmdb_ci',       type:'extends',   label:'extends'},
    {source:'cmdb_ci_appl', target:'cmdb_ci',        type:'extends',   label:'extends'},
    {source:'cmdb_ci_service',target:'cmdb_ci',      type:'extends',   label:'extends'},
    {source:'alm_hardware', target:'cmdb_ci',        type:'extends',   label:'extends'},
    {source:'task',         target:'sys_user',       type:'reference', label:'Assigned to',     field:'assigned_to'},
    {source:'task',         target:'sys_user_group', type:'reference', label:'Assignment group', field:'assignment_group'},
    {source:'task',         target:'cmdb_ci',        type:'reference', label:'CI',               field:'cmdb_ci'},
    {source:'incident',     target:'problem',        type:'reference', label:'Problem',          field:'problem_id'},
    {source:'problem',      target:'change_request', type:'reference', label:'Change',           field:'change_id'},
    {source:'sc_req_item',  target:'sc_request',     type:'reference', label:'Request',          field:'request'},
    {source:'sc_task',      target:'sc_req_item',    type:'reference', label:'RITM',             field:'request_item'},
    {source:'incident',     target:'kb_knowledge',   type:'reference', label:'KB article',       field:'knowledge'},
    {source:'ast_contract', target:'sys_user',       type:'reference', label:'Contract owner',   field:'contract_owner'},
    {source:'alm_hardware', target:'ast_contract',   type:'reference', label:'Lease contract',   field:'lease_contract'},
    {source:'sn_risk_risk', target:'cmdb_ci',        type:'reference', label:'Affected CI',      field:'affected_ci'},
    {source:'sn_hr_core_case',target:'sys_user',     type:'reference', label:'HR Subject',       field:'subject_person'},
    {source:'task',         target:'sys_user',       type:'reference', label:'Opened by',        field:'opened_by'},
    {source:'sys_user',     target:'sys_user_group', type:'reference', label:'Department',       field:'u_department'},
    {source:'sys_user',       target:'sys_user_group', type:'m2m',  label:'sys_user_grmember',   junction:'sys_user_grmember'},
    {source:'sys_user',       target:'sys_user_role',  type:'m2m',  label:'sys_user_has_role',   junction:'sys_user_has_role'},
    {source:'task',           target:'cmdb_ci',        type:'m2m',  label:'task_ci_assoc',       junction:'task_ci_assoc'},
    {source:'incident',       target:'sys_user_group', type:'m2m',  label:'incident_watcher',    junction:'task_ci_assoc'},
    {source:'sn_customerservice_case',target:'cmdb_ci',type:'m2m',  label:'sn_cs_case_to_ci',   junction:'sn_cs_case_to_ci'},
    {source:'problem',        target:'cmdb_ci',        type:'m2m',  label:'problem_ci_assoc',    junction:'problem_ci_assoc'},
    {source:'incident',      target:'problem',         type:'rel',  label:'Related problems',    query:'incident=${current.sys_id}'},
    {source:'cmdb_ci',       target:'incident',        type:'rel',  label:'Affected incidents',  query:'cmdb_ci=${current.sys_id}'},
    {source:'cmdb_ci',       target:'change_request',  type:'rel',  label:'Changes for CI',      query:'cmdb_ci=${current.sys_id}'},
    {source:'sys_user',      target:'incident',        type:'rel',  label:'Assigned incidents',  query:'assigned_to=${current.sys_id}'},
    {source:'ast_contract',  target:'alm_hardware',    type:'rel',  label:'Assets on contract',  query:'lease_contract=${current.sys_id}'},
    {source:'kb_knowledge',  target:'incident',        type:'rel',  label:'Linked incidents',    query:'knowledge=${current.sys_id}'},
    {source:'cmdb_ci_service',target:'cmdb_ci',        type:'rel',  label:'Service components',  query:'cmdb_ci_service=${current.sys_id}'},
    {source:'incident',      target:'task',            type:'view', label:'v_task_incident',     view:'v_task_incident'},
    {source:'change_request',target:'task',            type:'view', label:'v_task_change',       view:'v_task_change'},
    {source:'cmdb_ci_server',target:'cmdb_ci',         type:'view', label:'v_cmdb_ci_server',    view:'v_cmdb_ci_server'},
    {source:'cmdb_ci_appl',  target:'cmdb_ci',         type:'view', label:'v_cmdb_ci_appl',      view:'v_cmdb_ci_appl'},
  ],
  _schema_version: 1,
  _instance: {
    instance_name:    'dev12345',
    instance_url:     'https://dev12345.service-now.com',
    build_name:       'Yokohama',
    build_tag:        'glide-yokohama-02-07-2025__patch5-04-09-2025',
    build_date:       '04-09-2025_2244',
    node_count:       1,
    active_plugins:   142,
    active_packages:  38,
    active_languages: 1,
    exported_at:      '2025-05-01 09:12:33',
    exported_by:      'admin',
  },
  _stats: {
    counts: {
      // 20 nodes, 120 total fields across all nodes
      tables:               20,
      fields:               120,
      // reference-type fields counted across all node field lists
      references:           32,
      m2m_relationships:    6,
      named_relationships:  7,
      db_views:             4,
      // 4 views × 2 member tables each
      view_members:         8,
      extends_edges:        12,
      // global, sn_hr_core, sn_customerservice, sn_risk
      unique_scopes:        4,
      type_catalog_entries: 8,
    },
    coverage: {
      // 16 of 20 tables have at least one reference field
      tables_with_references:     16,
      tables_with_references_pct: 80.0,
      // 120 fields / 20 tables
      avg_fields_per_table:       6.0,
      // task children are 1 hop from task; nothing deeper in this demo
      deepest_inheritance_chain:  2,
    },
  },
  _capabilities: {
    recordCounts: { enabled: false },
  },
  _build: {
    startedAt:      '2025-05-01T09:12:28.000Z',
    elapsedMs:      248,
    builderVersion: '2.0.0',
  },
  _typeCatalog: {
    'string':          { label: 'String',      scalarType: 'string' },
    'integer':         { label: 'Integer',     scalarType: 'integer' },
    'reference':       { label: 'Reference',   scalarType: 'reference' },
    'boolean':         { label: 'True/False',  scalarType: 'boolean' },
    'glide_date_time': { label: 'Date/Time',   scalarType: 'glide_date_time' },
    'glide_date':      { label: 'Date',        scalarType: 'glide_date' },
    'html':            { label: 'HTML',        scalarType: 'html' },
    'currency':        { label: 'Currency',    scalarType: 'currency' },
  },
};

export const DOMAIN_DEFS = [
  { id:'org',     label:'① Organizational',   color:'var(--edge-ref)',
    patterns:['sys_user','core_company','sys_user_group','sys_user_role',
              'cmn_department','cmn_location','cmn_cost_center','alm_stockroom',
              'cmn_building','cmn_skill','sys_user_grmember','sys_group_has_role',
              'sys_user_has_role','sys_user_has_skill','sys_group_has_skill',
              'cmn_skill_contains','cmn_m2m_skill_model'] },
  { id:'task',    label:'② Task',              color:'#26c6da',
    patterns:['task','incident','problem','change_request','change_phase',
              'change_task','sc_request','sc_req_item','sc_task','sysapproval',
              'planned_task','pm_project','pm_project_task','rm_release','rm_feature',
              'rm_story','rm_defect','rm_sprint','rm_epic','rm_task','wm_order',
              'wm_task','sm_order','sm_task','hr_case','hr_task','hr_change',
              'facilities_request','ticket','issue','kb_submission','loaner_request',
              'grc_activity','grc_remediation','grc_observation','grc_audit',
              'grc_control_test','dmn_demand','dmn_decision','dmn_requirement',
              'chat_queue','vtb_task','metric_definition','metric_instance',
              'task_sla','task_ci','task_cmdb_ci_service','task_time_worked','task_outage'] },
  { id:'catalog', label:'③ Service Catalog',   color:'#06d6a0',
    patterns:['sc_cat','sc_cart','sc_ordered','sc_category','service_offering',
              'service_scope','service_in_scope','service_out_scope','service_commitment',
              'service_availability','service_subscribe','service_sla',
              'user_criteria','pc_product','pc_vendor','pc_hardware'] },
  { id:'cmdb',    label:'④ CMDB',              color:'#ff9f5a',
    patterns:['cmdb_ci','cmdb_rel','cmdb_serial','cmdb_software','cmdb_sam',
              'cmdb_running','cmdb_tcp','cmdb_ip','cmdb_lease','cmdb_depreciation',
              'cmdb_m2m','cmdb_processor','cmdb_printer','cmdb_kvm','cmdb_vmware',
              'dscy_','em_alert','em_event','discovery_','ecc_agent','ci_identifier'] },
  { id:'asset',   label:'⑤ Asset & Contract',  color:'#ef476f',
    patterns:['alm_asset','alm_hardware','alm_license','alm_consumable',
              'alm_transfer','alm_entitlement','alm_facility','alm_fixed',
              'ast_contract','ast_service','ast_warranty','ast_lease',
              'clm_m2m','clm_terms','proc_po','proc_rec','fm_expense',
              'fm_budget','fm_ci_rate','fm_contract_rate','fm_labor',
              'fm_task_rate','fm_distribution','fm_expense_allocation',
              'fm_relationship','fm_recurring','fm_rate_card','vndr_credit'] },
  { id:'model',   label:'⑥ Model Management',  color:'#ffd166',
    patterns:['cmdb_hardware_product','cmdb_software_product','cmdb_model_category',
              'cmdb_application_product','cmdb_consumable_product',
              'cmdb_contract_product','cmdb_serviceorder','cmdb_worktask_product',
              'cmdb_servicetask','cmdb_facreq','cmdb_factask',
              'cmdb_hr_case_product','cmdb_hr_task','cmdb_m2m_model',
              'cmdb_workorder_product','cmdb_model'] },
  { id:'sla',     label:'⑦ SLA',              color:'#ab47bc',
    patterns:['contract_sla','cmn_schedule','cmn_relative','cmn_other_schedule','sla_condition'] },
  { id:'kb',      label:'⑧ Knowledge',         color:'#66bb6a',
    patterns:['kb_knowledge','kb_feedback','kb_use','kb_category',
              'kb_knowledge_base','m2m_kb','m2m_document','dms_document'] },
  { id:'other',   label:'Other / Custom',       color:'#556070', patterns:[] }
];

export function getDomain(tableId) {
  for (const dom of DOMAIN_DEFS) {
    if (dom.patterns.some(p => tableId.startsWith(p))) return dom;
  }
  return DOMAIN_DEFS[DOMAIN_DEFS.length - 1];
}

export const SCOPE_PALETTE = [
  '#0EA5E9',
  '#63DF4E',
  '#6366F1',
  '#A855F7',
  '#F59E0B',
  '#10B981',
  '#F87171',
  '#38BDF8',
  '#FB7185',
  '#34D399',
  '#C084FC',
  '#FCD34D',
];

export const Config = Object.freeze({
  sim: {
    largeGraphThreshold: 200,
    maxFps: 30,
    settleAlpha: 0.005,
    chargeMag:  -2200,
    linkDistance: {
      extends: 110,
      m2m:     200,
      view:    180,
      ref:     160,
    },
    linkStrength: { large: 0.6, small: 0.3 },
    velocityDecay: { large: 0.5, small: 0.30 },
  },
  geomForce: {
    nodeWidth:      174,
    nodeHalfHeight:  22,
    fanStep:         10,
    maxFan:           1,
    minBezierDist:  174 * 1.3,
    minClippedLen:    8,
  },
  geomDomain: {
    nodeWidth:   162,
    halfHeight:   18,
    fanStep:      14,
    maxFan:        5,
    minDist:     162 * 2 + 20,
  },
  render: {
    maxNodesDefault: 10,
    hopDepthDefault:   1,
  },
});

export const LARGE_GRAPH  = Config.sim.largeGraphThreshold;
export const MAX_FPS      = Config.sim.maxFps;
export const SETTLE_ALPHA = Config.sim.settleAlpha;

export const INSP_OPEN_BY_DEFAULT = new Set(['properties', 'fields', 'inherited-fields', 'refs-out', 'cirel']);
